// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../../types";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * BFDProfile represents the settings of the bfd session that can be optionally associated with a BGP session.
 */
export class BFDProfile extends pulumi.CustomResource {
    /**
     * Get an existing BFDProfile resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): BFDProfile {
        return new BFDProfile(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:metallb.io/v1beta1:BFDProfile';

    /**
     * Returns true if the given object is an instance of BFDProfile.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is BFDProfile {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === BFDProfile.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"metallb.io/v1beta1" | undefined>;
    public readonly kind!: pulumi.Output<"BFDProfile" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta | undefined>;
    /**
     * BFDProfileSpec defines the desired state of BFDProfile.
     */
    public readonly spec!: pulumi.Output<outputs.metallb.v1beta1.BFDProfileSpec | undefined>;
    /**
     * BFDProfileStatus defines the observed state of BFDProfile.
     */
    public readonly status!: pulumi.Output<{[key: string]: any} | undefined>;

    /**
     * Create a BFDProfile resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: BFDProfileArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "metallb.io/v1beta1";
            resourceInputs["kind"] = "BFDProfile";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? args.spec : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(BFDProfile.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a BFDProfile resource.
 */
export interface BFDProfileArgs {
    apiVersion?: pulumi.Input<"metallb.io/v1beta1">;
    kind?: pulumi.Input<"BFDProfile">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * BFDProfileSpec defines the desired state of BFDProfile.
     */
    spec?: pulumi.Input<inputs.metallb.v1beta1.BFDProfileSpecArgs>;
    /**
     * BFDProfileStatus defines the observed state of BFDProfile.
     */
    status?: pulumi.Input<{[key: string]: any}>;
}
