// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../../types";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * BGPAdvertisement allows to advertise the IPs coming from the selected IPAddressPools via BGP, setting the parameters of the BGP Advertisement.
 */
export class BGPAdvertisement extends pulumi.CustomResource {
    /**
     * Get an existing BGPAdvertisement resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): BGPAdvertisement {
        return new BGPAdvertisement(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:metallb.io/v1beta1:BGPAdvertisement';

    /**
     * Returns true if the given object is an instance of BGPAdvertisement.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is BGPAdvertisement {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === BGPAdvertisement.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"metallb.io/v1beta1" | undefined>;
    public readonly kind!: pulumi.Output<"BGPAdvertisement" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta | undefined>;
    /**
     * BGPAdvertisementSpec defines the desired state of BGPAdvertisement.
     */
    public readonly spec!: pulumi.Output<outputs.metallb.v1beta1.BGPAdvertisementSpec | undefined>;
    /**
     * BGPAdvertisementStatus defines the observed state of BGPAdvertisement.
     */
    public readonly status!: pulumi.Output<{[key: string]: any} | undefined>;

    /**
     * Create a BGPAdvertisement resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: BGPAdvertisementArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "metallb.io/v1beta1";
            resourceInputs["kind"] = "BGPAdvertisement";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? (args.spec ? pulumi.output(args.spec).apply(inputs.metallb.v1beta1.bgpadvertisementSpecArgsProvideDefaults) : undefined) : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(BGPAdvertisement.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a BGPAdvertisement resource.
 */
export interface BGPAdvertisementArgs {
    apiVersion?: pulumi.Input<"metallb.io/v1beta1">;
    kind?: pulumi.Input<"BGPAdvertisement">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * BGPAdvertisementSpec defines the desired state of BGPAdvertisement.
     */
    spec?: pulumi.Input<inputs.metallb.v1beta1.BGPAdvertisementSpecArgs>;
    /**
     * BGPAdvertisementStatus defines the observed state of BGPAdvertisement.
     */
    status?: pulumi.Input<{[key: string]: any}>;
}
