// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../../types";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * CephBlockPool represents a Ceph Storage Pool
 */
export class CephBlockPool extends pulumi.CustomResource {
    /**
     * Get an existing CephBlockPool resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): CephBlockPool {
        return new CephBlockPool(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:ceph.rook.io/v1:CephBlockPool';

    /**
     * Returns true if the given object is an instance of CephBlockPool.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CephBlockPool {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CephBlockPool.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"ceph.rook.io/v1" | undefined>;
    public readonly kind!: pulumi.Output<"CephBlockPool" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta>;
    /**
     * NamedBlockPoolSpec allows a block pool to be created with a non-default name. This is more specific than the NamedPoolSpec so we get schema validation on the allowed pool names that can be specified.
     */
    public readonly spec!: pulumi.Output<outputs.ceph.v1.CephBlockPoolSpec>;
    /**
     * CephBlockPoolStatus represents the mirroring status of Ceph Storage Pool
     */
    public readonly status!: pulumi.Output<{[key: string]: any} | undefined>;

    /**
     * Create a CephBlockPool resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: CephBlockPoolArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "ceph.rook.io/v1";
            resourceInputs["kind"] = "CephBlockPool";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? args.spec : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(CephBlockPool.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a CephBlockPool resource.
 */
export interface CephBlockPoolArgs {
    apiVersion?: pulumi.Input<"ceph.rook.io/v1">;
    kind?: pulumi.Input<"CephBlockPool">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * NamedBlockPoolSpec allows a block pool to be created with a non-default name. This is more specific than the NamedPoolSpec so we get schema validation on the allowed pool names that can be specified.
     */
    spec?: pulumi.Input<inputs.ceph.v1.CephBlockPoolSpecArgs>;
    /**
     * CephBlockPoolStatus represents the mirroring status of Ceph Storage Pool
     */
    status?: pulumi.Input<{[key: string]: any}>;
}
