// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../../types";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * CephBucketTopic represents a Ceph Object Topic for Bucket Notifications
 */
export class CephBucketTopic extends pulumi.CustomResource {
    /**
     * Get an existing CephBucketTopic resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): CephBucketTopic {
        return new CephBucketTopic(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:ceph.rook.io/v1:CephBucketTopic';

    /**
     * Returns true if the given object is an instance of CephBucketTopic.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CephBucketTopic {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CephBucketTopic.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"ceph.rook.io/v1" | undefined>;
    public readonly kind!: pulumi.Output<"CephBucketTopic" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta>;
    /**
     * BucketTopicSpec represent the spec of a Bucket Topic
     */
    public readonly spec!: pulumi.Output<outputs.ceph.v1.CephBucketTopicSpec>;
    /**
     * BucketTopicStatus represents the Status of a CephBucketTopic
     */
    public readonly status!: pulumi.Output<{[key: string]: any} | undefined>;

    /**
     * Create a CephBucketTopic resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: CephBucketTopicArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "ceph.rook.io/v1";
            resourceInputs["kind"] = "CephBucketTopic";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? (args.spec ? pulumi.output(args.spec).apply(inputs.ceph.v1.cephBucketTopicSpecArgsProvideDefaults) : undefined) : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(CephBucketTopic.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a CephBucketTopic resource.
 */
export interface CephBucketTopicArgs {
    apiVersion?: pulumi.Input<"ceph.rook.io/v1">;
    kind?: pulumi.Input<"CephBucketTopic">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * BucketTopicSpec represent the spec of a Bucket Topic
     */
    spec?: pulumi.Input<inputs.ceph.v1.CephBucketTopicSpecArgs>;
    /**
     * BucketTopicStatus represents the Status of a CephBucketTopic
     */
    status?: pulumi.Input<{[key: string]: any}>;
}
