// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from '@pulumi/pulumi';
import { input as inputs, output as outputs } from '../../types';
import * as utilities from '../../utilities';

import { ObjectMeta } from '../../meta/v1';

/**
 * AppProject provides a logical grouping of applications, providing controls for: * where the apps may deploy to (cluster whitelist) * what may be deployed (repository whitelist, resource whitelist/blacklist) * who can access these applications (roles, OIDC group claims bindings) * and what they can do (RBAC policies) * automation access to these roles (JWT tokens)
 */
export class AppProject extends pulumi.CustomResource {
    /**
     * Get an existing AppProject resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): AppProject {
        return new AppProject(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:argoproj.io/v1alpha1:AppProject';

    /**
     * Returns true if the given object is an instance of AppProject.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AppProject {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AppProject.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<'argoproj.io/v1alpha1' | undefined>;
    public readonly kind!: pulumi.Output<'AppProject' | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta>;
    /**
     * AppProjectSpec is the specification of an AppProject
     */
    public readonly spec!: pulumi.Output<outputs.argoproj.v1alpha1.AppProjectSpec>;
    /**
     * AppProjectStatus contains status information for AppProject CRs
     */
    public readonly status!: pulumi.Output<outputs.argoproj.v1alpha1.AppProjectStatus | undefined>;

    /**
     * Create a AppProject resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: AppProjectArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs['apiVersion'] = 'argoproj.io/v1alpha1';
            resourceInputs['kind'] = 'AppProject';
            resourceInputs['metadata'] = args ? args.metadata : undefined;
            resourceInputs['spec'] = args ? args.spec : undefined;
            resourceInputs['status'] = args ? args.status : undefined;
        } else {
            resourceInputs['apiVersion'] = undefined /*out*/;
            resourceInputs['kind'] = undefined /*out*/;
            resourceInputs['metadata'] = undefined /*out*/;
            resourceInputs['spec'] = undefined /*out*/;
            resourceInputs['status'] = undefined /*out*/;
        }
        if (!opts.version) {
            opts = pulumi.mergeOptions(opts, { version: utilities.getVersion() });
        }
        super(AppProject.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a AppProject resource.
 */
export interface AppProjectArgs {
    apiVersion?: pulumi.Input<'argoproj.io/v1alpha1'>;
    kind?: pulumi.Input<'AppProject'>;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * AppProjectSpec is the specification of an AppProject
     */
    spec?: pulumi.Input<inputs.argoproj.v1alpha1.AppProjectSpecArgs>;
    /**
     * AppProjectStatus contains status information for AppProject CRs
     */
    status?: pulumi.Input<inputs.argoproj.v1alpha1.AppProjectStatusArgs>;
}
