// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from '@pulumi/pulumi';
import * as utilities from '../../utilities';

// Export members:
export * from './certificate';
export * from './certificateRequest';
export * from './clusterIssuer';
export * from './issuer';

// Import resources to register:
import { Certificate } from './certificate';
import { CertificateRequest } from './certificateRequest';
import { ClusterIssuer } from './clusterIssuer';
import { Issuer } from './issuer';

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case 'kubernetes:cert-manager.io/v1:Certificate':
                return new Certificate(name, <any>undefined, { urn });
            case 'kubernetes:cert-manager.io/v1:CertificateRequest':
                return new CertificateRequest(name, <any>undefined, { urn });
            case 'kubernetes:cert-manager.io/v1:ClusterIssuer':
                return new ClusterIssuer(name, <any>undefined, { urn });
            case 'kubernetes:cert-manager.io/v1:Issuer':
                return new Issuer(name, <any>undefined, { urn });
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule('crds', 'cert-manager.io/v1', _module);
