// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from '@pulumi/pulumi';
import * as utilities from '../../utilities';

// Export members:
export * from './trafficSplit';

// Import resources to register:
import { TrafficSplit } from './trafficSplit';

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case 'kubernetes:split.smi-spec.io/v1alpha2:TrafficSplit':
                return new TrafficSplit(name, <any>undefined, { urn });
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule('crds', 'split.smi-spec.io/v1alpha2', _module);
