#![allow(incomplete_features)]
#![feature(generic_const_exprs)]

/// A module for the various types used & generated by the [`model!()`] proc-macro.
pub mod model;

pub use surreal_simple_querybuilder_proc_macro::model;

/// Contains a trait for simplifying the building of relationships between nodes
pub mod node_builder;

/// Contains the query builder for simplifying the building of Surreal QL queries.
/// Particularely useful when composing variables and conditional queries
pub mod querybuilder;

/// Contains the `Foreign<T>` type used to represent fields that may or may not be
/// loaded.
// pub mod foreign;
pub mod foreign_key;

pub mod prelude;
