use std::fmt;

use anyhow::Context;
use bson::DateTime;
use chrono::{Duration, Utc};

use common::sum;
use oauth2::{
    basic::{BasicClient, BasicTokenType},
    reqwest::async_http_client,
    AuthUrl, AuthorizationCode, ClientId, ClientSecret, CsrfToken, EmptyExtraTokenFields,
    RedirectUrl, Scope, StandardTokenResponse, TokenResponse, TokenUrl,
};
use redis::{Commands, FromRedisValue, RedisError};
use serde::{Deserialize, Serialize};
use url::Url;

use crate::app::user::{AccountOauth, OauthProvider, Role, TokenType, User};

#[derive(Debug, Deserialize, Serialize)]
enum GithubScopes {
    #[serde(rename = "public_repo")]
    PublicRepo,
    #[serde(rename = "user:email")]
    UserEmail,
}

#[derive(Debug, Deserialize, Serialize)]
struct RemoteOauthDataGithub {
    login: String,
    id: String,
    node_id: String,
    avatar_url: String,
    gravatar_id: String,
    url: String,
    html_url: String,
    followers_url: String,
    following_url: String,
    gists_url: String,
    starred_url: String,
    subscriptions_url: String,
    organizations_url: String,
    repos_url: String,
    events_url: String,
    received_events_url: String,

    #[serde(rename = "type")]
    account_type: String,
    site_admin: String,
    name: String,
    company: String,
    blog: String,
    location: String,
    email: Option<String>,
    hireable: String,
    bio: String,
    twitter_username: String,
    public_repos: String,
    public_gists: String,
    followers: String,
    following: String,
    created_at: String,
    updated_at: String,
}

enum ProviderType {
    Credentials,
}

// impl From<RemoteOauthDataGithub> for ProfileOauth {
//     fn from(remote: RemoteOauthDataGithub) -> Self {
//         let mut remote_name = remote.name.split("");
//         let first_name = remote_name.next().map(String::from);
//         let last_name = remote_name.next().map(String::from);

//         //  let mut rng = rand::thread_rng();
//         let autogenerated_id = uuid::Uuid::new_v4().to_string();
//         Self {
//             // id
//             // scopes
//             first_name,
//             last_name,
//             username: format!("{}-{autogenerated_id}", remote.login),
//             email: remote.email,
//             email_verified: false,
//         }
//     }
// }

// TODO: Account linking
// Linking Accounts to Users happen automatically, only when they have the same e-mail address, and the user is currently signed in. Check the FAQ for more information why this is a requirement.

#[async_trait::async_trait]
pub(crate) trait OauthProviderTrait {
    // type Confr;

    fn client(self) -> BasicClient;

    /// Generate the authorization URL to which we'll redirect the user.
    fn generate_auth_url(&self) -> AuthUrlData;

    async fn fetch_oauth_account(
        &self,
        code: AuthorizationCode,
    ) -> anyhow::Result<User, OauthProviderError>;

    // fn exchange_code_for_token(self) {
    //        let token_res = client
    //     .exchange_code(code)
    //     .request_async(async_http_client)
    //     .await;
    // }
}

const REDIRECT_URL: &str = "http://localhost:8080";
// use derive_more::{Add, Display, From, Into};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TypedAuthUrl(pub Url);

// impl IntoInner for TypedAuthUrl {

// }

impl fmt::Display for TypedAuthUrl {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

// impl Into<Url> for TypedAuthUrl {
//     // fn from(url: Url) -> Self {
//     //     Self(url)
//     // }

//     fn into(self) -> Url {
//         self.0
//     }
// }

impl TypedAuthUrl {
    pub fn get_authorization_code(&self) -> AuthorizationCode {
        let value = self.get_query_param_value("code");
        AuthorizationCode::new(value.into_owned())
    }

    pub(crate) fn get_csrf_state(&self) -> TypedCsrfState {
        let value = self.get_query_param_value("state");
        TypedCsrfState(CsrfToken::new(value.into_owned()))
    }

    fn get_query_param_value(&self, query_param: &str) -> std::borrow::Cow<str> {
        let state_pair = self
            .0
            .query_pairs()
            .find(|pair| {
                let &(ref key, _) = pair;
                key == query_param
            })
            .expect("Not found. TODO: Handle error properly later");
        let (_, value) = state_pair;
        value
    }
}

#[derive(Debug, Clone)]
struct OauthConfig {
    client_id: ClientId,
    client_secret: ClientSecret,
    auth_url: AuthUrl,
    token_url: TokenUrl,
    scopes: Vec<Scope>,
}

#[derive(Debug, Clone)]
pub(crate) struct GithubConfig {
    basic_config: OauthConfig,
}

impl GithubConfig {
    pub fn new() -> Self {
        let basic_config = OauthConfig {
            // Get first two from environment variable
            client_id: ClientId::new("57d332c258954615aac7".to_string()),
            client_secret: ClientSecret::new("e41a1fb86af01532fe640a2d79ad6608c3774261".into()),
            auth_url: AuthUrl::new("https://github.com/login/oauth/authorize".to_string())
                .expect("Invalid authorization endpoint URL"),
            token_url: TokenUrl::new("https://github.com/login/oauth/access_token".to_string())
                .expect("Invalid token endpoint URL"),
            scopes: vec![
                Scope::new("public_repo".into()),
                Scope::new("read:user".into()),
                Scope::new("user:email".into()),
            ],
        };
        Self { basic_config }
    }
}

#[derive(Debug, thiserror::Error)]
pub(crate) enum CsrfStateError {
    #[error("The csrf code provided by the provider is invalid. Does not match the one sent. Potential spoofing")]
    InvalidCsrfToken,

    #[error(transparent)]
    RedisError(#[from] RedisError),

    #[error(transparent)]
    SerializationError(#[from] serde_json::Error),
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub(crate) struct TypedCsrfState(CsrfToken);
pub(crate) struct TypedCsrfStateData {
    csrf_token: CsrfToken,
    provider: OauthProvider,
}

// impl FromRedisValue for TypedCsrfState {
//     fn from_redis_value(v: &redis::Value) -> redis::RedisResult<Self> {
//         v.
//         todo!()
//     }
// }
// pub(crate) struct TypedCsrfState(CsrfToken);

// #[derive(Debug, Clone, Serialize, Deserialize)]
// pub(crate) struct VerifiedState{

// };

impl TypedCsrfState {
    const CSRF_STATE_REDIS_KEY: &'static str = "CSRF_STATE_REDIS_KEY";

    fn redis_key(&self) -> String {
        format!(
            "{}{:?}",
            Self::CSRF_STATE_REDIS_KEY,
            self.0.secret().as_str()
        )
        // format!(
        //     "{}{:?}{:?}",
        //     Self::CSRF_STATE_REDIS_KEY,
        //     self.provider,
        //     self.csrf_token.secret().as_str()
        // )
    }

    pub(crate) fn cache(
        &self,
        provider: OauthProvider,
        con: &mut redis::Connection,
    ) -> anyhow::Result<(), CsrfStateError> {
        let m = serde_json::to_string(&provider)?;
        // let m = serde_json::to_string(&self.0)?;

        let _: () = con.set(self.redis_key(), m)?;
        Ok(())
    }

    pub(crate) fn verify(
        &self,
        con: &mut redis::Connection,
    ) -> Result<OauthProvider, CsrfStateError> {
        let csrf_state: String = con.get(self.redis_key())?;
        // let csrf_state: Self = serde_json::from_str(csrf_state.as_str())?;
        // let csrf_state: OauthProvider = serde_json::from_str(csrf_state.as_str())?;

        if let Ok(d) = serde_json::from_str::<OauthProvider>(csrf_state.as_str()) {
            return Ok(d);
        } else {
            return Err(CsrfStateError::InvalidCsrfToken);
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub(crate) struct AuthUrlData {
    pub(crate) authorize_url: TypedAuthUrl,
    pub(crate) csrf_state: TypedCsrfState,
}

#[derive(thiserror::Error, Debug)]
pub(crate) enum OauthProviderError {
    #[error("Failed to fetch user profile")]
    FailedToFetchUserProfile,
    // FailedToFetchUserProfile(#[from] anyhow::Error),
}

#[async_trait::async_trait]
impl OauthProviderTrait for GithubConfig {
    fn client(self) -> BasicClient {
        BasicClient::new(
            self.basic_config.client_id,
            Some(self.basic_config.client_secret),
            self.basic_config.auth_url,
            Some(self.basic_config.token_url),
        )
        // This example will be running its own server at localhost:8080.
        // See below for the server implementation.
        .set_redirect_uri(
            RedirectUrl::new("http://localhost:8080".to_string()).expect("Invalid redirect URL"),
        )
    }

    /// Generate the authorization URL to which we'll redirect the user.
    fn generate_auth_url(&self) -> AuthUrlData {
        // let c = self;
        let (authorize_url, csrf_state) = self
            .clone()
            .client()
            .authorize_url(CsrfToken::new_random)
            // This example is requesting access to the user's public repos and email.
            // .add_scope(Scope::new("public_repo".to_string()))
            // .add_scope(Scope::new("read:user".to_string()))
            // .add_scope(Scope::new("user:email".to_string()))
            .add_scopes(self.basic_config.clone().scopes)
            .url();
        AuthUrlData {
            authorize_url: TypedAuthUrl(authorize_url),
            csrf_state: TypedCsrfState(csrf_state),
        }
    }

    async fn fetch_oauth_account(
        &self,
        code: AuthorizationCode,
    ) -> anyhow::Result<User, OauthProviderError> {
        let token_res = self
            .clone()
            .client()
            .exchange_code(code)
            .request_async(async_http_client)
            .await;

        if let Ok(token) = token_res {
            // NB: Github returns a single comma-separated "scope" parameter instead of multiple
            // space-separated scopes. Github-specific clients can parse this scope into
            // multiple scopes by splitting at the commas. Note that it's not safe for the
            // library to do this by default because RFC 6749 allows scopes to contain commas.
            // println!("TOKENNNN{:?}", token);
            // println!("Accesssss{:?}", token.access_token().secret().as_str());
            let url = "https://api.github.com/user";
            let body = reqwest::Client::new()
                    .get(url)
                                .header("accept", "application/vnd.github.v3+json")
            .header("user-agent","Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36")
                    // .header("Authorization", format!("Bearer {}",token.access_token().secret().as_str()))
                    .bearer_auth(token.clone().access_token().secret().as_str())
                    .send()
                    .await
                    .unwrap()
                    .text()
                    .await
                    .unwrap();

            print!("FGREWRTBODY:{body}");

            let profile = serde_json::from_str::<RemoteOauthDataGithub>(body.as_str()).unwrap();
            // TODO: First search the database if the user exists, if exists, just update, else create
            // User::find({profile: profile.id, provider: provider});

            let expiration = token.expires_in().unwrap_or(std::time::Duration::new(0, 0));
            let expiration = Duration::from_std(expiration).unwrap_or(Duration::seconds(0));
            let expires_at = Utc::now() + expiration;

            let scopes = token
                .scopes()
                .map(|s| {
                    s.iter()
                        .map(|comma_separated| comma_separated.split(','))
                        .flatten()
                        .map(String::from)
                        .collect::<Vec<_>>()
                })
                .unwrap_or_default();
            println!("Github returned the following scopes:\n{:?}\n", scopes.clone());

            let account = AccountOauth::builder()
                .id(profile.id.clone())
                .account_type(profile.account_type)
                .provider(OauthProvider::Github)
                .provider_account_id(OauthProvider::Github)
                .access_token(token.access_token().secret().into())
                .refresh_token(token.refresh_token().map(|rf| rf.secret().into()))
                .expires_at(Some(expires_at))
                .token_type(Some(TokenType::Bearer))
                .scopes(scopes)
                .build();


            let autogenerated_id = uuid::Uuid::new_v4().to_string();
            let user = User::builder()
                .username(format!("{}-{autogenerated_id}", profile.name))
                .email(profile.email)
                .roles(vec![Role::User])
                .accounts(vec![account])
                .age(None)
                .password(None)
                .build();

            // TODO: Search user from db by github id and provider. If present, upsert other attributes, otherwise create
            return Ok(user);
        }

        return Err(OauthProviderError::FailedToFetchUserProfile);
    }
}
