use chrono::{Duration, Utc};
use oauth2::{
    reqwest::async_http_client, AuthUrl, AuthorizationCode, ClientId, ClientSecret, CsrfToken,
    PkceCodeVerifier, RedirectUrl, RevocationUrl, Scope, TokenResponse, TokenUrl,
};
use serde::{Deserialize, Serialize};

use super::utils::{
    OauthConfig, OauthConfigTrait, OauthError, OauthProviderTrait, OauthResult, OauthUrl,
    REDIRECT_URL,
};
use crate::app::user::{AccountOauth, OauthProvider, Role, TokenType, User};

#[derive(Debug, Deserialize, Serialize)]
enum GoogleScopes {
    #[serde(rename = "public_repo")]
    PublicRepo,
    #[serde(rename = "user:email")]
    UserEmail,
}

#[derive(Debug, Deserialize, Serialize)]
struct GoogleUserData {
    sub: String,
    name: String,
    given_name: String,
    family_name: String,
    picture: String,
    email: String,
    email_verified: bool,
    locale: String,
}

#[derive(Debug, Clone)]
pub(crate) struct GoogleConfig {
    basic_config: OauthConfig,
}

impl GoogleConfig {
    pub fn new() -> Self {
        let k = CsrfToken::new_random;
        let basic_config = OauthConfig::builder()
            .client_id(ClientId::new(
                "855174209543-i23grd1ts6qbq568dfl43hla7hv9cn4u.apps.googleusercontent.com"
                    .to_string(),
            ))
            .client_secret(ClientSecret::new(
                "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".into(),
            ))
            .auth_url(
                AuthUrl::new("https://accounts.google.com/o/oauth2/v2/auth".to_string())
                    .expect("Invalid authorization endpoint URL"),
            )
            .token_url(
                TokenUrl::new("https://www.googleapis.com/oauth2/v4/token".to_string())
                    .expect("Invalid token endpoint URL"),
            )
            .redirect_url(RedirectUrl::new(REDIRECT_URL.to_string()).expect("Invalid redirect URL"))
            .scopes(vec![
                Scope::new("profile".into()),
                Scope::new("email".into()),
                // Scope::new("openid".into()),
                // Scope::new("https://www.googleapis.com/auth/plus.me".into()),
                // Scope::new("https://www.googleapis.com/auth/calendar".into()),
            ])
            .provider(OauthProvider::Google)
            .revocation_url(
                RevocationUrl::new("https://oauth2.googleapis.com/revoke".into()).expect("msg"),
            )
            .build();
        Self { basic_config }
    }
}

#[async_trait::async_trait]
impl OauthProviderTrait for GoogleConfig {
    fn basic_config(&self) -> OauthConfig {
        self.basic_config.to_owned()
    }

    async fn fetch_oauth_account(
        &self,
        code: AuthorizationCode,
        pkce_code_verifier: PkceCodeVerifier,
    ) -> OauthResult<User> {
        let token = self
            .basic_config()
            .client()
            .exchange_code(code)
            .set_pkce_verifier(pkce_code_verifier)
            .request_async(async_http_client)
            .await
            .map_err(|e| OauthError::TokenFetchFailed(e.to_string()))?;

        let profile = OauthUrl("https://www.googleapis.com/oauth2/v3/userinfo")
            .fetch_resource::<GoogleUserData>(&token, None)
            .await?;

        let expiration = token.expires_in().unwrap_or(std::time::Duration::new(0, 0));
        let expiration = Duration::from_std(expiration).unwrap_or(Duration::seconds(0));
        let expires_at = Utc::now() + expiration;
        let scopes = self
            .basic_config()
            .scopes
            .iter()
            .map(|x| x.to_string())
            .collect::<Vec<String>>();

        let account = AccountOauth::builder()
            .id(profile.sub.to_string())
            .account_type("oauth".into())
            .provider(OauthProvider::Google)
            .provider_account_id(OauthProvider::Google)
            .access_token(token.access_token().secret().into())
            .refresh_token(token.refresh_token().map(|rf| rf.secret().into()))
            .expires_at(Some(expires_at))
            .token_type(Some(TokenType::Bearer))
            .scopes(scopes)
            .build();

        let autogenerated_id = uuid::Uuid::new_v4().to_string();
        let user = User::builder()
            .username(format!("{}-{}", profile.sub, autogenerated_id))
            .email(Some(profile.email))
            .roles(vec![Role::User])
            .accounts(vec![account])
            .age(None)
            .password(None)
            .build();

        Ok(user)
    }
}
