// Don't Edit. This is autogenerated.
export interface IFluvioAppOyelowo {
    loadBalancer: LoadBalancer;
    service: Service;
    scLog: string;
    tls: boolean;
    imagePullSecrets: any[];
    image: Image;
    cert: Cert;
    authorizationConfigMap: string;
    scPod: ScPod;
    spuPod: SpuPod;
    rbac: Rbac;
    serviceAccount: ServiceAccount;
    podSecurityContext: ServiceAnnotations;
    connectorPrefixes: string;
}
interface ServiceAccount {
    name: string;
}
interface Rbac {
    create: boolean;
}
interface SpuPod {
    resources: Resources;
    nodeSelector: ServiceAnnotations;
    storageClass?: any;
    baseNodePort: number;
    extraContainers: any[];
}
interface ScPod {
    resources: Resources;
    nodeSelector: ServiceAnnotations;
    publicPort: number;
    nodePort: number;
    extraContainers: any[];
}
interface Resources {
    requests: Requests;
    limits: Requests;
}
interface Requests {
    memory: string;
}
interface Cert {
    caCert: string;
    tls: string;
    domain: string;
}
interface Image {
    registry: string;
    tag: string;
    pullPolicy: string;
}
interface Service {
    type: string;
}
interface LoadBalancer {
    serviceAnnotations: ServiceAnnotations;
}
interface ServiceAnnotations {}
