// Don't Edit. This is autogenerated.
export interface INackNats {
	jetstream: Jetstream;
	namespaced: boolean;
	nameOverride: string;
	namespaceOverride: string;
	imagePullSecrets: any[];
	serviceAccountName: string;
	podAnnotations: PodAnnotations;
	securityContext: PodAnnotations;
	containerSecurityContext: PodAnnotations;
	affinity: PodAnnotations;
	nodeSelector: PodAnnotations;
	tolerations: any[];
	resources: PodAnnotations;
}
interface PodAnnotations {}
interface Jetstream {
	enabled: boolean;
	image: string;
	pullPolicy: string;
	replicas: number;
	nats: Nats;
	tls: Tls;
}
interface Tls {
	enabled: boolean;
	secretName?: any;
	settings: Settings;
}
interface Settings {
	client_cert: string;
	client_key: string;
	client_ca: string;
	timeout: number;
}
interface Nats {
	url?: any;
}
