// Don't Edit. This is autogenerated.
export interface INatsKafkaNats {
    nameOverride: string;
    fullnameOverride: string;
    namespaceOverride: string;
    replicaCount: number;
    image: Image;
    natskafka: Natskafka;
}
interface Natskafka {
    reconnectInterval: number;
    connectTimeout: number;
    logging: Logging;
    monitoring: Monitoring;
    deploymentLabels: DeploymentLabels;
    podLabels: DeploymentLabels;
    configPath?: any;
    additionalArguments: any[];
    additionalVolumes: DeploymentLabels;
    additionalVolumeMounts: DeploymentLabels;
    resources: DeploymentLabels;
    affinity: DeploymentLabels;
    nodeSelector: DeploymentLabels;
    tolerations: any[];
    nats: Nats;
    connect: any[];
}
interface Nats {
    servers: any[];
    connectTimeout: number;
    maxReconnects: number;
    reconnectWait: number;
}
interface DeploymentLabels {}
interface Monitoring {
    httpHost: string;
    httpPort: number;
    httpsPort: number;
    tls: Tls;
}
interface Tls {
    secret: string;
    root: string;
    cert: string;
    key: string;
}
interface Logging {
    time: boolean;
    debug: boolean;
    trace: boolean;
    colors: boolean;
    pid: boolean;
}
interface Image {
    repository: string;
    pullPolicy: string;
    tagOverride: string;
}
