// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export * from "./smartModule";
export * from "./topic";

// Import resources to register:
import { SmartModule } from "./smartModule";
import { Topic } from "./topic";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:fluvio.infinyon.com/v2:SmartModule":
                return new SmartModule(name, <any>undefined, { urn })
            case "kubernetes:fluvio.infinyon.com/v2:Topic":
                return new Topic(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("crds", "fluvio.infinyon.com/v2", _module)
