DEFINE TABLE planet SCHEMAFULL;
DEFINE FIELD id ON planet TYPE record<planet>;
DEFINE FIELD population ON planet TYPE int;
DEFINE FIELD firstName ON planet TYPE string;
DEFINE FIELD tags ON planet TYPE array;
DEFINE FIELD created ON planet TYPE datetime;
DEFINE TABLE student SCHEMAFULL;
DEFINE FIELD school ON student TYPE string;
DEFINE FIELD age ON student TYPE int;
DEFINE FIELD class ON student TYPE string;
DEFINE FIELD id ON student TYPE record<student>;