DEFINE TABLE animal SCHEMAFULL;
DEFINE TABLE eats SCHEMAFULL;
DEFINE TABLE crop SCHEMAFULL;
DEFINE FIELD color ON crop TYPE string;
DEFINE FIELD id ON crop TYPE record<crop>;
DEFINE FIELD place ON eats TYPE string;
DEFINE FIELD out ON eats TYPE record;
DEFINE FIELD createdAt ON eats TYPE datetime;
DEFINE FIELD id ON eats TYPE record<eats>;
DEFINE FIELD in ON eats TYPE record;
DEFINE FIELD attributes ON animal TYPE array;
DEFINE FIELD createdAt ON animal TYPE datetime;
DEFINE FIELD species ON animal TYPE string;
DEFINE FIELD id ON animal TYPE record<animal>;