// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export * from "./derivedStream";
export * from "./managedConnector";
export * from "./partition";
export * from "./smartModule";
export * from "./spu";
export * from "./spuGroup";
export * from "./tableFormat";
export * from "./topic";

// Import resources to register:
import { DerivedStream } from "./derivedStream";
import { ManagedConnector } from "./managedConnector";
import { Partition } from "./partition";
import { SmartModule } from "./smartModule";
import { Spu } from "./spu";
import { SpuGroup } from "./spuGroup";
import { TableFormat } from "./tableFormat";
import { Topic } from "./topic";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:fluvio.infinyon.com/v1:DerivedStream":
                return new DerivedStream(name, <any>undefined, { urn })
            case "kubernetes:fluvio.infinyon.com/v1:ManagedConnector":
                return new ManagedConnector(name, <any>undefined, { urn })
            case "kubernetes:fluvio.infinyon.com/v1:Partition":
                return new Partition(name, <any>undefined, { urn })
            case "kubernetes:fluvio.infinyon.com/v1:SmartModule":
                return new SmartModule(name, <any>undefined, { urn })
            case "kubernetes:fluvio.infinyon.com/v1:Spu":
                return new Spu(name, <any>undefined, { urn })
            case "kubernetes:fluvio.infinyon.com/v1:SpuGroup":
                return new SpuGroup(name, <any>undefined, { urn })
            case "kubernetes:fluvio.infinyon.com/v1:TableFormat":
                return new TableFormat(name, <any>undefined, { urn })
            case "kubernetes:fluvio.infinyon.com/v1:Topic":
                return new Topic(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("crds", "fluvio.infinyon.com/v1", _module)
