// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../../types";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

export class SmartModule extends pulumi.CustomResource {
    /**
     * Get an existing SmartModule resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): SmartModule {
        return new SmartModule(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:fluvio.infinyon.com/v1:SmartModule';

    /**
     * Returns true if the given object is an instance of SmartModule.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SmartModule {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SmartModule.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"fluvio.infinyon.com/v1" | undefined>;
    public readonly kind!: pulumi.Output<"SmartModule" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta | undefined>;
    public readonly spec!: pulumi.Output<outputs.fluvio.v1.SmartModuleSpec>;
    public readonly status!: pulumi.Output<{[key: string]: any} | undefined>;

    /**
     * Create a SmartModule resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: SmartModuleArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "fluvio.infinyon.com/v1";
            resourceInputs["kind"] = "SmartModule";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? args.spec : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SmartModule.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a SmartModule resource.
 */
export interface SmartModuleArgs {
    apiVersion?: pulumi.Input<"fluvio.infinyon.com/v1">;
    kind?: pulumi.Input<"SmartModule">;
    metadata?: pulumi.Input<ObjectMeta>;
    spec?: pulumi.Input<inputs.fluvio.v1.SmartModuleSpecArgs>;
    status?: pulumi.Input<{[key: string]: any}>;
}
