// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from '@pulumi/pulumi';
import * as utilities from '../../utilities';

// Export members:
export * from './sealedSecret';

// Import resources to register:
import { SealedSecret } from './sealedSecret';

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case 'kubernetes:bitnami.com/v1alpha1:SealedSecret':
                return new SealedSecret(name, <any>undefined, { urn });
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule('crds', 'bitnami.com/v1alpha1', _module);
