// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export * from "./objectBucket";
export * from "./objectBucketClaim";

// Import resources to register:
import { ObjectBucket } from "./objectBucket";
import { ObjectBucketClaim } from "./objectBucketClaim";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:objectbucket.io/v1alpha1:ObjectBucket":
                return new ObjectBucket(name, <any>undefined, { urn })
            case "kubernetes:objectbucket.io/v1alpha1:ObjectBucketClaim":
                return new ObjectBucketClaim(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("crds", "objectbucket.io/v1alpha1", _module)
